#%RAML 1.0 DataType

description: A super hero
properties:
  id:
    type: number
    description: The system generated ID of the hero in the database
    example: 1
    required: false
  name:
    type: string
    description: The hero's name
    example: Superman
    required: true
